name: meson
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: sudo apt-get install meson ninja util-linux
      - name: build
        run: |
          mkdir build
          cd build
          meson build
          sudo meson install

