name: meson
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build util-linux libmount-dev
          # can't install as user because we need `sudo meson install` later
          sudo pip3 install meson
      - name: build
        run: |
          mkdir build
          cd build
          meson ..
          meson compile
          sudo meson install

