name: build-rpm
on: [push]
jobs:
  runs-on: ubuntu-20.04
  container: bcumming/bci-base-rpmbuilder:testing
  build:
    steps:
      - uses: actions/checkout@v2

      - name: build srpm
        run: |
          make rpm
          make install-suid

  test:
      - name: build srpm
        run: |
          ls -ahl
          pwd

